libra/website

website/siteConfig.js
website/static/js/forms.js

Remove search bar from all form pages
Yes

Lib 1 remove search from form2

---

website/core/ContactForm/text-input.js
website/pages/en/partner_form.js
website/static/css/forms.css
website/static/js/segment.js

We need to add a few more fields to the partner form.
Yes

LIB-16: Added three new fields to the partner form

---

docs/community/contributing.md

Saw a couple of complaints in the project that build failed because of missing this and that dependency. This should make the instruction more clear

Update the instructions of building the project

---

docs/move-overview.md

Updating the example code to match the (future) change at the "libra" repository:
https://github.com/libra/libra/pull/263
The example code had two unused variables. https://github.com/libra/libra/pull/263 will remove those, but the example should be updated.
Yes.
Test instructions are available at: https://github.com/libra/libra/pull/263
The actual code change: https://github.com/libra/libra/pull/263

Getting Started With Move: Updated EarmarkedLibraCoin

---

website/pages/en/index.js

Update instructions to checkout testnet branch

update instructions to checkout testnet branch

---

website/core/ContactForm/country-codes.js

There were a few missing countries in the newsletter form.
Yes

LIB-17: Added mssing countries

---

docs/my-first-transaction.md

Added instructions to checkout the testnet branch. This update to the setup instructions will help avoid errors like the one mentioned in this issue - https://github.com/libra/libra/issues/358
Yes
Review the doc.

[website] Add instructions to checkout testnet branch

---

.gitmodules
scripts/build_docs.sh

Working to add previews to PRs.

Modifying build script to add Netlify PR doc previews

---

.gitignore
README.md

Updates gitignore file

---

website/sidebars.json

Modifying sidebar temporarily.

Modify sidebar temporarily

---

website/sidebars.json

Modifying sidebar temporarily.

Add guides to sidebar navigation

---

website/blog/2019-09-12-libra-developer-spotlight.md

Incorrect link was fixed
Yes
N/A
N/A

LIB-126: Fixed a blog link

---

website/blog/2019-09-26-libra-bft-protocol.md

Updated author

---

website/core/ContactForm/select-input.js
website/core/ContactForm/text-input.js
website/pages/en/partner_form.js
website/static/css/forms.css
website/static/js/cookie_banner.js
website/static/js/forms.js
website/static/js/segment.js

1. Updates to the fields collected in the partner form
2. Fixed IE issues for segment
3. Fixed IE issues for form
4. Fixed IE styling issues
yes
Fully tested by QA team
N/A

LIB-166: Updated forms to include all the new fields

---

website/blog/2019-10-21-simplifying-payloads.md
website/blog/2019-10-22-simplifying-payloads.md

Adding Simplifying Payloads blog post
Yes
Post was verified on staging

[LIB-186]: Simplifying Payloads blog post

---

website/blog/2019-10-02-libra-developer-update.md

Update blog post with legal notification
Yes
N/A
N/A

LIB-153: Added legal text

---

website/blog/2019-11-15-5-months-and-growing-strong.md

Blog post [LIB-196]
**Don't merge until 12PST!**
Yes
Verified on staging

Core Summit Blogpost

---

website/blog/2019-11-15-5-months-and-growing-strong.md

Copy updates to most recent blog post
Yes
Verified on staging

Lib 196 core summit post updates

---

website/blog/2019-11-15-5-months-and-growing-strong.md

Copy edits to blog post
Yes
Verified on staging

Core Summit Blogpost Revision

---

website/blog/2019-12-10-about-the-cla-process.md

CLA Blog Post to go out 12/10/2019
Yes
Verified on staging

[LIB-210]: CLA Blog Post

---

docs/community/contributing.md

Update CLA copy and move it above Contributing to Libra Core
Yes
Verified/reviewed on staging

Update CLA copy

---

website/siteConfig.js

Need to expand sidebar to show all blog posts.

Show all blog posts on sidebar

---

docs/libra-protocol.md

A more direct and appropriate link to the blockchain technical paper.
Yes
Visual
N/A

Better link to the Libra Blockchain paper

---

website/blog/2020-01-08-how-gas-works-on-libra-blockchain.md

LIB-204: Remove second chain from post

---

website/blog/2020-01-16-steering-committee-now-governs-libra-technical-development.md

Lib 223 tsc blog post 1/16

---

website/blog/2020-01-23-full-node-basics.md

LIB-224: Add Full Node Basics Blog Post

---

website/blog/2020-02-26-libra-core-roadmap-3.md
website/blog/2020-02-28-libra-core-roadmap-3.md

Lib 284 libra core roadmap3 blog post

---

website/blog/2019-06-18-the-path-forward.md
website/blog/2019-08-14-libra-bug-bounty.md
website/blog/2019-09-12-libra-developer-spotlight.md
website/blog/2019-09-26-libra-bft-protocol.md
website/blog/2019-10-02-libra-developer-update.md
website/blog/2019-10-22-simplifying-payloads.md
website/blog/2019-10-29-a-guide-to-running-libra-validators.md
website/blog/2019-11-09-libra-consensus-protocol.md
website/blog/2019-11-15-5-months-and-growing-strong.md
website/blog/2019-12-10-about-the-cla-process.md
website/blog/2019-12-17-libra-core-roadmap-2.md
website/blog/2020-01-08-how-gas-works-on-libra-blockchain.md
website/blog/2020-01-14-reconfiguration-is-live-on-testnet.md
website/blog/2020-01-16-steering-committee-now-governs-libra-technical-development.md
website/blog/2020-01-23-full-node-basics.md
website/blog/2020-02-28-libra-core-roadmap-3.md
website/blog/2020-03-06-how-to-use-the-end-to-end-tests-framework-in-move.md

Redirects all blog links to the new location
Yes
N/A
N/A

Redirect blog

---

website/package-lock.json
website/package.json

update dfuzr-docusaurus version, force rebuild of dev site with netlify.

force netlify rebuild

---

README.md

Grammar fix
Yes
Visual verification should suffice
N/A

Add period to sentence in README

---

docs/move-overview.md

Better clarification in the module example re: earmarks
Yes
ran site locally
N/A

Update earmark content wording in Move overview

---

docs/community/contributing.md

xbuild, what is that?

---

website/siteConfig.js
website/static/css/custom.css

Developers links on libra.org has changed. This updates the nav on the developers site to match.

Update developers nav link url to libra.org/developers from libra.org/open-source-developers

---

website/siteConfig.js

LIB-579: add governance to subnav

---

.circleci/config.yml

USE_SSH = false

---

docs/my-first-transaction.md

Test the new GHA site deploy
Yes
This is the test
N/A

Testing new deploy

---

docs/my-first-transaction.md

Testing whether GHA runs on fork
Yes
Live
N/A

Testing deploy from fork

---

scripts/build_docs.sh

Update the Libra submodule to latest checkout. It was 7 months old.
Yes
Ran the build script and didn't have file not found errors any longer
N/A

Update Libra submodule

---

docs/move-overview.md
docs/my-first-transaction.md
docs/run-move-locally.md

- Fix code samples in move-overview.md so that they will compile
- Update commands and sample output in my-first-transaction.md for
shorter addresses and multicurrency accounts. Also update the output
shown in the "Sample Outputs of Additional Query Commands" section.
- Update run-move-locally.md for multicurrency accounts.
Current docs do not match the implementation
Yes
I ran the code samples through the Move compiler and made sure that they compile, and I walked through most of the steps in the documents to check that the commands and sample output match the current status.

Update developer docs to match the current implementation

---

docs/welcome-to-libra.md

Fixing a link that was landing users on the blog page
Yes
N/A
N/A

LIB-550: Fixed the internal link

---

src/pages/reference-wallet/index.js

Updating Wallet demo link.
Yes
N/A
N/A

Add new URL for wallet demo

---

docs/move/overview.md

Update move overview with fixes
Yes
Netlify build
N/A

Update Move overview with some fixes and links

---

docs/my-first-transaction.md
docs/run-local-network.md
docs/run-move-locally.md

- Update CLI output to match the latest results
- Update libra-swarm usage in run-local-network.md (especially using hyphens instead underscores in option names and adding the -f option)
Yes
I ran through the steps in a local build (not using testnet).

Change documents about Move to match the system as of 2020-07-24

---

docs/core/run-move-locally.md
docs/welcome-to-libra.md
package-lock.json

Get us more in sync with `master` before we launch. We should do this semi-often so we have less work when we rename `staging` into `master`
Yes
Ran site locally
https://github.com/libra/website/pull/215

Update staging with appropriate commits from master
